/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ApiErrorType - api_error
 */
public enum ApiErrorType {
    API_ERROR("api_error");

    @JsonValue
    public final String value;

    private ApiErrorType(String value) {
        this.value = value;
    }
}
