/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ApiError - API related Errors
 */

public class ApiError {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    public String code;

    public ApiError withCode(String code) {
        this.code = code;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public ApiError withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * api_error
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public ApiErrorType type;

    public ApiError withType(ApiErrorType type) {
        this.type = type;
        return this;
    }
    
    public ApiError(){}
}
