/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class App {
    /**
     * Specify the channel through which the payment must be processed.
     */
    @JsonProperty("channel")
    public String channel;

    public App withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * Customer phone number associated with a wallet for payment.
     */
    @JsonProperty("phone")
    public String phone;

    public App withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    /**
     * Specify the provider through which the payment must be processed.
     */
    @JsonProperty("provider")
    public AppProvider provider;

    public App withProvider(AppProvider provider) {
        this.provider = provider;
        return this;
    }
    
    public App(@JsonProperty("channel") String channel, @JsonProperty("phone") String phone, @JsonProperty("provider") AppProvider provider) {
        this.channel = channel;
        this.phone = phone;
        this.provider = provider;
  }
}
