/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AuthorizationRequestAction - Type of authorization to run. Can be one of 'CAPTURE' , 'VOID'
 */
public enum AuthorizationRequestAction {
    CAPTURE("CAPTURE"),
    VOID_("VOID");

    @JsonValue
    public final String value;

    private AuthorizationRequestAction(String value) {
        this.value = value;
    }
}
