/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class AuthorizationRequest {
    /**
     * Type of authorization to run. Can be one of 'CAPTURE' , 'VOID'
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("action")
    public AuthorizationRequestAction action;

    public AuthorizationRequest withAction(AuthorizationRequestAction action) {
        this.action = action;
        return this;
    }
    
    /**
     * The amount if you are running a 'CAPTURE'
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    public Double amount;

    public AuthorizationRequest withAmount(Double amount) {
        this.amount = amount;
        return this;
    }
    
    public AuthorizationRequest(){}
}
