/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AuthorizationInPaymentsEntityStatus - One of SUCCESS or PENDING
 */
public enum AuthorizationInPaymentsEntityStatus {
    SUCCESS("SUCCESS"),
    PENDING("PENDING");

    @JsonValue
    public final String value;

    private AuthorizationInPaymentsEntityStatus(String value) {
        this.value = value;
    }
}
