/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AuthorizationInPaymentsEntityAction - One of CAPTURE or VOID
 */
public enum AuthorizationInPaymentsEntityAction {
    CAPTURE("CAPTURE"),
    VOID_("VOID");

    @JsonValue
    public final String value;

    private AuthorizationInPaymentsEntityAction(String value) {
        this.value = value;
    }
}
