/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * AuthenticationErrorType - authentication_error
 */
public enum AuthenticationErrorType {
    AUTHENTICATION_ERROR("authentication_error");

    @JsonValue
    public final String value;

    private AuthenticationErrorType(String value) {
        this.value = value;
    }
}
