/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CardPaymentMethod - The card payment object is used to make payment using either plain card number, saved card instrument id or using cryptogram 
 */

public class CardPaymentMethod {
    @JsonProperty("card")
    public Card card;

    public CardPaymentMethod withCard(Card card) {
        this.card = card;
        return this;
    }
    
    public CardPaymentMethod(@JsonProperty("card") Card card) {
        this.card = card;
  }
}
