/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CardEMIPaymentMethod {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emi")
    public CardEMI emi;

    public CardEMIPaymentMethod withEmi(CardEMI emi) {
        this.emi = emi;
        return this;
    }
    
    public CardEMIPaymentMethod(){}
}
