/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CardCardBankName - One of ["Kotak", "ICICI", "RBL", "BOB", "Standard Chartered"]. Card bank name, required for EMI payments. This is the bank user has selected for EMI
 */
public enum CardCardBankName {
    KOTAK("Kotak"),
    ICICI("ICICI"),
    RBL("RBL"),
    BOB("BOB"),
    STANDARD_CHARTERED("Standard Chartered");

    @JsonValue
    public final String value;

    private CardCardBankName(String value) {
        this.value = value;
    }
}
