/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CardEMICardBankName - Card bank name, required for EMI payments. This is the bank user has selected for EMI. One of ["hdfc, "kotak", "icici", "rbl", "bob", "standard chartered", "axis", "au", "yes", "sbi", "fed", "hsbc", "citi", "amex"]
 */
public enum CardEMICardBankName {
    HDFC("hdfc"),
    KOTAK("kotak"),
    ICICI("icici"),
    RBL("rbl"),
    BOB("bob"),
    STANDARD_CHARTERED("standard chartered"),
    AXIS("axis"),
    AU("au"),
    YES("yes"),
    SBI("sbi"),
    FED("fed"),
    HSBC("hsbc"),
    CITI("citi"),
    AMEX("amex");

    @JsonValue
    public final String value;

    private CardEMICardBankName(String value) {
        this.value = value;
    }
}
