/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CardlessEMIQueries {
    /**
     * Amount of the order. OrderId of the order. Either of `order_id` or `amount` is mandatory.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    public Double amount;

    public CardlessEMIQueries withAmount(Double amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * Details of the customer for whom eligibility is being checked.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_details")
    public CustomerDetailsCardlessEMI customerDetails;

    public CardlessEMIQueries withCustomerDetails(CustomerDetailsCardlessEMI customerDetails) {
        this.customerDetails = customerDetails;
        return this;
    }
    
    /**
     * OrderId of the order. Either of `order_id` or `amount` is mandatory.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public CardlessEMIQueries withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    public CardlessEMIQueries(){}
}
