/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CardlessEMIProvider - One of [`flexmoney`, `zestmoney`, `hdfc`, `icici`, `cashe`, `idfc`, `kotak`]
 */
public enum CardlessEMIProvider {
    FLEXMONEY("flexmoney"),
    ZESTMONEY("zestmoney"),
    HDFC("hdfc"),
    ICICI("icici"),
    CASHE("cashe"),
    IDFC("idfc"),
    KOTAK("kotak");

    @JsonValue
    public final String value;

    private CardlessEMIProvider(String value) {
        this.value = value;
    }
}
