/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class CardOffer {
    /**
     * Bank Name of Card.
     */
    @JsonProperty("bank_name")
    public String bankName;

    public CardOffer withBankName(String bankName) {
        this.bankName = bankName;
        return this;
    }
    
    @JsonProperty("scheme_name")
    public String[] schemeName;

    public CardOffer withSchemeName(String[] schemeName) {
        this.schemeName = schemeName;
        return this;
    }
    
    @JsonProperty("type")
    public String[] type;

    public CardOffer withType(String[] type) {
        this.type = type;
        return this;
    }
    
    public CardOffer(@JsonProperty("bank_name") String bankName, @JsonProperty("scheme_name") String[] schemeName, @JsonProperty("type") String[] type) {
        this.bankName = bankName;
        this.schemeName = schemeName;
        this.type = type;
  }
}
