/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class CardlessEMIPaymentMethod {
    @JsonProperty("cardless_emi")
    public CardlessEMI cardlessEmi;

    public CardlessEMIPaymentMethod withCardlessEmi(CardlessEMI cardlessEmi) {
        this.cardlessEmi = cardlessEmi;
        return this;
    }
    
    public CardlessEMIPaymentMethod(@JsonProperty("cardless_emi") CardlessEMI cardlessEmi) {
        this.cardlessEmi = cardlessEmi;
  }
}
