/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CardlessEMIEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("emi_plans")
    public EMIPlansArray[] emiPlans;

    public CardlessEMIEntity withEmiPlans(EMIPlansArray[] emiPlans) {
        this.emiPlans = emiPlans;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_method")
    public String paymentMethod;

    public CardlessEMIEntity withPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    public CardlessEMIEntity(){}
}
