/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CashbackDetailsCashbackType - Type of discount
 */
public enum CashbackDetailsCashbackType {
    FLAT("flat"),
    PERCENTAGE("percentage");

    @JsonValue
    public final String value;

    private CashbackDetailsCashbackType(String value) {
        this.value = value;
    }
}
