/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CashbackDetails {
    /**
     * Type of discount
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cashback_type")
    public CashbackDetailsCashbackType cashbackType;

    public CashbackDetails withCashbackType(CashbackDetailsCashbackType cashbackType) {
        this.cashbackType = cashbackType;
        return this;
    }
    
    /**
     * Value of Discount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cashback_value")
    public String cashbackValue;

    public CashbackDetails withCashbackValue(String cashbackValue) {
        this.cashbackValue = cashbackValue;
        return this;
    }
    
    /**
     * Maximum Value of Cashback allowed.
     */
    @JsonProperty("max_cashback_amount")
    public String maxCashbackAmount;

    public CashbackDetails withMaxCashbackAmount(String maxCashbackAmount) {
        this.maxCashbackAmount = maxCashbackAmount;
        return this;
    }
    
    public CashbackDetails(@JsonProperty("max_cashback_amount") String maxCashbackAmount) {
        this.maxCashbackAmount = maxCashbackAmount;
  }
}
