/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * CreateRefundRequestRefundSpeed - Speed at which the refund is processed. It's an optional field with default being STANDARD
 */
public enum CreateRefundRequestRefundSpeed {
    STANDARD("STANDARD"),
    INSTANT("INSTANT");

    @JsonValue
    public final String value;

    private CreateRefundRequestRefundSpeed(String value) {
        this.value = value;
    }
}
