/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateRefundRequest {
    /**
     * Amount to be refunded. Should be lesser than or equal to the transaction amount. (Decimals allowed)
     */
    @JsonProperty("refund_amount")
    public Double refundAmount;

    public CreateRefundRequest withRefundAmount(Double refundAmount) {
        this.refundAmount = refundAmount;
        return this;
    }
    
    /**
     * An unique ID to associate the refund with. Provie alphanumeric values
     */
    @JsonProperty("refund_id")
    public String refundId;

    public CreateRefundRequest withRefundId(String refundId) {
        this.refundId = refundId;
        return this;
    }
    
    /**
     * A refund note for your reference.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_note")
    public String refundNote;

    public CreateRefundRequest withRefundNote(String refundNote) {
        this.refundNote = refundNote;
        return this;
    }
    
    /**
     * Speed at which the refund is processed. It's an optional field with default being STANDARD
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_speed")
    public CreateRefundRequestRefundSpeed refundSpeed;

    public CreateRefundRequest withRefundSpeed(CreateRefundRequestRefundSpeed refundSpeed) {
        this.refundSpeed = refundSpeed;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_splits")
    public VendorSplit[] refundSplits;

    public CreateRefundRequest withRefundSplits(VendorSplit[] refundSplits) {
        this.refundSplits = refundSplits;
        return this;
    }
    
    public CreateRefundRequest(@JsonProperty("refund_amount") Double refundAmount, @JsonProperty("refund_id") String refundId) {
        this.refundAmount = refundAmount;
        this.refundId = refundId;
  }
}
