/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class CreateTerminalRequest {
    /**
     * merchant’s internal terminal id
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("terminal_id")
    public String terminalId;

    public CreateTerminalRequest withTerminalId(String terminalId) {
        this.terminalId = terminalId;
        return this;
    }
    
    /**
     * terminal name to be assigned by merchants
     */
    @JsonProperty("terminal_name")
    public String terminalName;

    public CreateTerminalRequest withTerminalName(String terminalName) {
        this.terminalName = terminalName;
        return this;
    }
    
    /**
     * phone number assigned to the terminal
     */
    @JsonProperty("terminal_phone_no")
    public String terminalPhoneNo;

    public CreateTerminalRequest withTerminalPhoneNo(String terminalPhoneNo) {
        this.terminalPhoneNo = terminalPhoneNo;
        return this;
    }
    
    public CreateTerminalRequest(@JsonProperty("terminal_name") String terminalName, @JsonProperty("terminal_phone_no") String terminalPhoneNo) {
        this.terminalName = terminalName;
        this.terminalPhoneNo = terminalPhoneNo;
  }
}
