/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Cryptogram - OK
 */

public class Cryptogram {
    /**
     * last 4 digits of original card number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_display")
    public String cardDisplay;

    public Cryptogram withCardDisplay(String cardDisplay) {
        this.cardDisplay = cardDisplay;
        return this;
    }
    
    /**
     * token pan expiry month
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_expiry_mm")
    public String cardExpiryMm;

    public Cryptogram withCardExpiryMm(String cardExpiryMm) {
        this.cardExpiryMm = cardExpiryMm;
        return this;
    }
    
    /**
     * token pan expiry year
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_expiry_yy")
    public String cardExpiryYy;

    public Cryptogram withCardExpiryYy(String cardExpiryYy) {
        this.cardExpiryYy = cardExpiryYy;
        return this;
    }
    
    /**
     * token pan number
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_number")
    public String cardNumber;

    public Cryptogram withCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
        return this;
    }
    
    /**
     * cryptogram
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cryptogram")
    public String cryptogram;

    public Cryptogram withCryptogram(String cryptogram) {
        this.cryptogram = cryptogram;
        return this;
    }
    
    /**
     * instrument_id of saved instrument
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("instrument_id")
    public String instrumentId;

    public Cryptogram withInstrumentId(String instrumentId) {
        this.instrumentId = instrumentId;
        return this;
    }
    
    /**
     * TRID issued by card networks
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("token_requestor_id")
    public String tokenRequestorId;

    public Cryptogram withTokenRequestorId(String tokenRequestorId) {
        this.tokenRequestorId = tokenRequestorId;
        return this;
    }
    
    public Cryptogram(){}
}
