/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * CustomerDetailsCardlessEMI - Details of the customer for whom eligibility is being checked.
 */

public class CustomerDetailsCardlessEMI {
    /**
     * Phone Number of the customer
     */
    @JsonProperty("customer_phone")
    public String customerPhone;

    public CustomerDetailsCardlessEMI withCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
        return this;
    }
    
    public CustomerDetailsCardlessEMI(@JsonProperty("customer_phone") String customerPhone) {
        this.customerPhone = customerPhone;
  }
}
