/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class EligibilityCardlessEMIRequest {
    @JsonProperty("queries")
    public CardlessEMIQueries queries;

    public EligibilityCardlessEMIRequest withQueries(CardlessEMIQueries queries) {
        this.queries = queries;
        return this;
    }
    
    public EligibilityCardlessEMIRequest(@JsonProperty("queries") CardlessEMIQueries queries) {
        this.queries = queries;
  }
}
