/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class EligibleCardlessEMIEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("eligibility")
    public String eligibility;

    public EligibleCardlessEMIEntity withEligibility(String eligibility) {
        this.eligibility = eligibility;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_details")
    public CardlessEMIEntity entityDetails;

    public EligibleCardlessEMIEntity withEntityDetails(CardlessEMIEntity entityDetails) {
        this.entityDetails = entityDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_type")
    public String entityType;

    public EligibleCardlessEMIEntity withEntityType(String entityType) {
        this.entityType = entityType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_value")
    public String entityValue;

    public EligibleCardlessEMIEntity withEntityValue(String entityValue) {
        this.entityValue = entityValue;
        return this;
    }
    
    public EligibleCardlessEMIEntity(){}
}
