/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class EligiblePaylater {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("eligibility")
    public String eligibility;

    public EligiblePaylater withEligibility(String eligibility) {
        this.eligibility = eligibility;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_details")
    public PaylaterEntity entityDetails;

    public EligiblePaylater withEntityDetails(PaylaterEntity entityDetails) {
        this.entityDetails = entityDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_type")
    public String entityType;

    public EligiblePaylater withEntityType(String entityType) {
        this.entityType = entityType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity_value")
    public String entityValue;

    public EligiblePaylater withEntityValue(String entityValue) {
        this.entityValue = entityValue;
        return this;
    }
    
    public EligiblePaylater(){}
}
