/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class EligibilityOffersRequest {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("filters")
    public OfferFilters filters;

    public EligibilityOffersRequest withFilters(OfferFilters filters) {
        this.filters = filters;
        return this;
    }
    
    @JsonProperty("queries")
    public OfferQueries queries;

    public EligibilityOffersRequest withQueries(OfferQueries queries) {
        this.queries = queries;
        return this;
    }
    
    public EligibilityOffersRequest(@JsonProperty("queries") OfferQueries queries) {
        this.queries = queries;
  }
}
