/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class EMIOffer {
    /**
     * Bank Name
     */
    @JsonProperty("bank_name")
    public String bankName;

    public EMIOffer withBankName(String bankName) {
        this.bankName = bankName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("tenures")
    public Long[] tenures;

    public EMIOffer withTenures(Long[] tenures) {
        this.tenures = tenures;
        return this;
    }
    
    /**
     * Type of emi offer. Possible values are `credit_card_emi`, `debit_card_emi`, `cardless_emi`
     */
    @JsonProperty("type")
    public String type;

    public EMIOffer withType(String type) {
        this.type = type;
        return this;
    }
    
    public EMIOffer(@JsonProperty("bank_name") String bankName, @JsonProperty("type") String type) {
        this.bankName = bankName;
        this.type = type;
  }
}
