/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * ErrorDetailsInPaymentsEntity - The error details are present only for failed payments
 */

public class ErrorDetailsInPaymentsEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_code")
    public String errorCode;

    public ErrorDetailsInPaymentsEntity withErrorCode(String errorCode) {
        this.errorCode = errorCode;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_description")
    public String errorDescription;

    public ErrorDetailsInPaymentsEntity withErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_reason")
    public String errorReason;

    public ErrorDetailsInPaymentsEntity withErrorReason(String errorReason) {
        this.errorReason = errorReason;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error_source")
    public String errorSource;

    public ErrorDetailsInPaymentsEntity withErrorSource(String errorSource) {
        this.errorSource = errorSource;
        return this;
    }
    
    public ErrorDetailsInPaymentsEntity(){}
}
