/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * ErrorResponseType - One of ["invalid_request_error", "authentication_error", "rate_limit_error", "validation_error", "api_error"]
 */
public enum ErrorResponseType {
    INVALID_REQUEST_ERROR("invalid_request_error"),
    AUTHENTICATION_ERROR("authentication_error"),
    RATE_LIMIT_ERROR("rate_limit_error"),
    VALIDATION_ERROR("validation_error"),
    API_ERROR("api_error");

    @JsonValue
    public final String value;

    private ErrorResponseType(String value) {
        this.value = value;
    }
}
