/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchPGReconRequest {
    @JsonProperty("filters")
    public FetchPGReconRequestFilters filters;

    public FetchPGReconRequest withFilters(FetchPGReconRequestFilters filters) {
        this.filters = filters;
        return this;
    }
    
    /**
     * To fetch the next set of settlements, pass the cursor received in the response to the next API call. 
     *  To receive the data for the first time, pass the cursor as null. 
     *  Limit would be number of settlements that you want to receive.
     */
    @JsonProperty("pagination")
    public FetchPGReconRequestPagination pagination;

    public FetchPGReconRequest withPagination(FetchPGReconRequestPagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
    public FetchPGReconRequest(@JsonProperty("filters") FetchPGReconRequestFilters filters, @JsonProperty("pagination") FetchPGReconRequestPagination pagination) {
        this.filters = filters;
        this.pagination = pagination;
  }
}
