/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchPGReconRequestFilters {
    /**
     * Specify the end date till when you want the settlement reconciliation details.
     */
    @JsonProperty("end_date")
    public String endDate;

    public FetchPGReconRequestFilters withEndDate(String endDate) {
        this.endDate = endDate;
        return this;
    }
    
    /**
     * Specify the start date from when you want the settlement reconciliation details.
     */
    @JsonProperty("start_date")
    public String startDate;

    public FetchPGReconRequestFilters withStartDate(String startDate) {
        this.startDate = startDate;
        return this;
    }
    
    public FetchPGReconRequestFilters(@JsonProperty("end_date") String endDate, @JsonProperty("start_date") String startDate) {
        this.endDate = endDate;
        this.startDate = startDate;
  }
}
