/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchSettlementReconRequestPagination - To fetch the next set of settlements, pass the cursor received in the response to the next API call. 
 *  To receive the data for the first time, pass the cursor as null. 
 *  Limit would be number of settlements that you want to receive.
 */

public class FetchSettlementReconRequestPagination {
    /**
     * Specifies from where the next set of settlement details should be fetched.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cursor")
    public String cursor;

    public FetchSettlementReconRequestPagination withCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }
    
    /**
     * The number of settlements you want to fetch. Maximum limit is 1000, default value is 10.
     */
    @JsonProperty("limit")
    public Long limit;

    public FetchSettlementReconRequestPagination withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    public FetchSettlementReconRequestPagination(@JsonProperty("limit") Long limit) {
        this.limit = limit;
  }
}
