/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchSettlementRecon - OK
 */

public class FetchSettlementRecon {
    /**
     * Specifies from where the next set of settlement details should be fetched.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cursor")
    public String cursor;

    public FetchSettlementRecon withCursor(String cursor) {
        this.cursor = cursor;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public FetchSettlementReconData[] data;

    public FetchSettlementRecon withData(FetchSettlementReconData[] data) {
        this.data = data;
        return this;
    }
    
    /**
     * Number of settlements you want to fetch in the next iteration.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("limit")
    public Long limit;

    public FetchSettlementRecon withLimit(Long limit) {
        this.limit = limit;
        return this;
    }
    
    public FetchSettlementRecon(){}
}
