/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * FetchAllSavedInstrumentsInstrumentStatus - Status of the saved instrument.
 */
public enum FetchAllSavedInstrumentsInstrumentStatus {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

    @JsonValue
    public final String value;

    private FetchAllSavedInstrumentsInstrumentStatus(String value) {
        this.value = value;
    }
}
