/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchSettlementReconRequest {
    /**
     * Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
     */
    @JsonProperty("filters")
    public FetchSettlementReconRequestFilters filters;

    public FetchSettlementReconRequest withFilters(FetchSettlementReconRequestFilters filters) {
        this.filters = filters;
        return this;
    }
    
    /**
     * To fetch the next set of settlements, pass the cursor received in the response to the next API call. 
     *  To receive the data for the first time, pass the cursor as null. 
     *  Limit would be number of settlements that you want to receive.
     */
    @JsonProperty("pagination")
    public FetchSettlementReconRequestPagination pagination;

    public FetchSettlementReconRequest withPagination(FetchSettlementReconRequestPagination pagination) {
        this.pagination = pagination;
        return this;
    }
    
    public FetchSettlementReconRequest(@JsonProperty("filters") FetchSettlementReconRequestFilters filters, @JsonProperty("pagination") FetchSettlementReconRequestPagination pagination) {
        this.filters = filters;
        this.pagination = pagination;
  }
}
