/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * FetchSettlementReconRequestFilters - Specify either the Settlement ID, Settlement UTR, or start date and end date to fetch the settlement details.
 */

public class FetchSettlementReconRequestFilters {
    /**
     * List of settlement IDs for which you want the settlement reconciliation details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_settlement_ids")
    public Long[] cfSettlementIds;

    public FetchSettlementReconRequestFilters withCfSettlementIds(Long[] cfSettlementIds) {
        this.cfSettlementIds = cfSettlementIds;
        return this;
    }
    
    /**
     * Specify the end date till when you want the settlement reconciliation details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("end_date")
    public String endDate;

    public FetchSettlementReconRequestFilters withEndDate(String endDate) {
        this.endDate = endDate;
        return this;
    }
    
    /**
     * List of settlement UTRs for which you want the settlement reconciliation details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_utrs")
    public String[] settlementUtrs;

    public FetchSettlementReconRequestFilters withSettlementUtrs(String[] settlementUtrs) {
        this.settlementUtrs = settlementUtrs;
        return this;
    }
    
    /**
     * Specify the start date from when you want the settlement reconciliation details.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("start_date")
    public String startDate;

    public FetchSettlementReconRequestFilters withStartDate(String startDate) {
        this.startDate = startDate;
        return this;
    }
    
    public FetchSettlementReconRequestFilters(){}
}
