/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchPGReconData {
    /**
     * Amount that is adjusted from the settlement amount because of any credit/debit event such as refund, refund_reverse etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("adjustment")
    public Double adjustment;

    public FetchPGReconData withAdjustment(Double adjustment) {
        this.adjustment = adjustment;
        return this;
    }
    
    /**
     * Other adjustment remarks.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("adjustment_remarks")
    public String adjustmentRemarks;

    public FetchPGReconData withAdjustmentRemarks(String adjustmentRemarks) {
        this.adjustmentRemarks = adjustmentRemarks;
        return this;
    }
    
    /**
     * Net amount that is settled after considering the adjustments, settlement charge and tax.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount_settled")
    public Double amountSettled;

    public FetchPGReconData withAmountSettled(Double amountSettled) {
        this.amountSettled = amountSettled;
        return this;
    }
    
    /**
     * Cashfree Payments unique ID to identify a payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_payment_id")
    public Long cfPaymentId;

    public FetchPGReconData withCfPaymentId(Long cfPaymentId) {
        this.cfPaymentId = cfPaymentId;
        return this;
    }
    
    /**
     * Unique ID to identify the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_settlement_id")
    public Long cfSettlementId;

    public FetchPGReconData withCfSettlementId(Long cfSettlementId) {
        this.cfSettlementId = cfSettlementId;
        return this;
    }
    
    /**
     * Specifies whether the dispute was closed in favor of the merchant or customer. /n Possible values - Merchant, Customer
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("closed_in_favor_of")
    public String closedInFavorOf;

    public FetchPGReconData withClosedInFavorOf(String closedInFavorOf) {
        this.closedInFavorOf = closedInFavorOf;
        return this;
    }
    
    /**
     * Customer email.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_email")
    public String customerEmail;

    public FetchPGReconData withCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
        return this;
    }
    
    /**
     * Customer name.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_name")
    public String customerName;

    public FetchPGReconData withCustomerName(String customerName) {
        this.customerName = customerName;
        return this;
    }
    
    /**
     * Customer phone number.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_phone")
    public String customerPhone;

    public FetchPGReconData withCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
        return this;
    }
    
    /**
     * Category of the dispute - Dispute code and the reason for dispute is shown.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dispute_category")
    public String disputeCategory;

    public FetchPGReconData withDisputeCategory(String disputeCategory) {
        this.disputeCategory = disputeCategory;
        return this;
    }
    
    /**
     * Note regarding the dispute.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dispute_note")
    public String disputeNote;

    public FetchPGReconData withDisputeNote(String disputeNote) {
        this.disputeNote = disputeNote;
        return this;
    }
    
    /**
     * Date and time when the dispute was resolved.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("dispute_resolved_on")
    public String disputeResolvedOn;

    public FetchPGReconData withDisputeResolvedOn(String disputeResolvedOn) {
        this.disputeResolvedOn = disputeResolvedOn;
        return this;
    }
    
    /**
     * Recon
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity")
    public String entity;

    public FetchPGReconData withEntity(String entity) {
        this.entity = entity;
        return this;
    }
    
    /**
     * Amount of the event. Example, refund amount, dispute amount, payment amount, etc.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_amount")
    public Double eventAmount;

    public FetchPGReconData withEventAmount(Double eventAmount) {
        this.eventAmount = eventAmount;
        return this;
    }
    
    /**
     * Curreny type - INR.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_currency")
    public String eventCurrency;

    public FetchPGReconData withEventCurrency(String eventCurrency) {
        this.eventCurrency = eventCurrency;
        return this;
    }
    
    /**
     * Unique ID associated with the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_id")
    public String eventId;

    public FetchPGReconData withEventId(String eventId) {
        this.eventId = eventId;
        return this;
    }
    
    /**
     * Amount that is part of the settlement corresponding to the event.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_settlement_amount")
    public Double eventSettlementAmount;

    public FetchPGReconData withEventSettlementAmount(Double eventSettlementAmount) {
        this.eventSettlementAmount = eventSettlementAmount;
        return this;
    }
    
    /**
     * Status of the event. Example - SUCCESS, FAILED, PENDING, CANCELLED.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_status")
    public String eventStatus;

    public FetchPGReconData withEventStatus(String eventStatus) {
        this.eventStatus = eventStatus;
        return this;
    }
    
    /**
     * Time associated with the event. Example, transaction time, dispute initiation time
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_time")
    public String eventTime;

    public FetchPGReconData withEventTime(String eventTime) {
        this.eventTime = eventTime;
        return this;
    }
    
    /**
     * The event type can be SETTLEMENT, PAYMENT, REFUND, REFUND_REVERSAL, DISPUTE, DISPUTE_REVERSAL, CHARGEBACK, CHARGEBACK_REVERSAL, OTHER_ADJUSTMENT.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_type")
    public String eventType;

    public FetchPGReconData withEventType(String eventType) {
        this.eventType = eventType;
        return this;
    }
    
    /**
     * The amount which was passed at the order creation time.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_amount")
    public Double orderAmount;

    public FetchPGReconData withOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
        return this;
    }
    
    /**
     * Unique order ID. Alphanumeric and only '-' and '_' allowed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public FetchPGReconData withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    /**
     * Payment amount captured.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_amount")
    public Double paymentAmount;

    public FetchPGReconData withPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
        return this;
    }
    
    /**
     * The start time of the time range of the payments considered for the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_from")
    public String paymentFrom;

    public FetchPGReconData withPaymentFrom(String paymentFrom) {
        this.paymentFrom = paymentFrom;
        return this;
    }
    
    /**
     * Service charge applicable for the payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_service_charge")
    public Double paymentServiceCharge;

    public FetchPGReconData withPaymentServiceCharge(Double paymentServiceCharge) {
        this.paymentServiceCharge = paymentServiceCharge;
        return this;
    }
    
    /**
     * Service tax applicable on the payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_service_tax")
    public Double paymentServiceTax;

    public FetchPGReconData withPaymentServiceTax(Double paymentServiceTax) {
        this.paymentServiceTax = paymentServiceTax;
        return this;
    }
    
    /**
     * The end time of time range of the payments considered for the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_till")
    public String paymentTill;

    public FetchPGReconData withPaymentTill(String paymentTill) {
        this.paymentTill = paymentTill;
        return this;
    }
    
    /**
     * Date and time when the payment was initiated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_time")
    public String paymentTime;

    public FetchPGReconData withPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
        return this;
    }
    
    /**
     * Unique transaction reference number of the payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_utr")
    public String paymentUtr;

    public FetchPGReconData withPaymentUtr(String paymentUtr) {
        this.paymentUtr = paymentUtr;
        return this;
    }
    
    /**
     * Reason for settlement failure.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("reason")
    public String reason;

    public FetchPGReconData withReason(String reason) {
        this.reason = reason;
        return this;
    }
    
    /**
     * The bank reference number for the refund.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_arn")
    public String refundArn;

    public FetchPGReconData withRefundArn(String refundArn) {
        this.refundArn = refundArn;
        return this;
    }
    
    /**
     * An unique ID to associate the refund with.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_id")
    public String refundId;

    public FetchPGReconData withRefundId(String refundId) {
        this.refundId = refundId;
        return this;
    }
    
    /**
     * A refund note for your reference.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_note")
    public String refundNote;

    public FetchPGReconData withRefundNote(String refundNote) {
        this.refundNote = refundNote;
        return this;
    }
    
    /**
     * Date and time when the refund was processed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_processed_at")
    public String refundProcessedAt;

    public FetchPGReconData withRefundProcessedAt(String refundProcessedAt) {
        this.refundProcessedAt = refundProcessedAt;
        return this;
    }
    
    /**
     * Remarks on the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("remarks")
    public String remarks;

    public FetchPGReconData withRemarks(String remarks) {
        this.remarks = remarks;
        return this;
    }
    
    /**
     * Indicates if it is CREDIT/DEBIT sale.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sale_type")
    public String saleType;

    public FetchPGReconData withSaleType(String saleType) {
        this.saleType = saleType;
        return this;
    }
    
    /**
     * Service charge applicable on the settlement amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_charge")
    public Double serviceCharge;

    public FetchPGReconData withServiceCharge(Double serviceCharge) {
        this.serviceCharge = serviceCharge;
        return this;
    }
    
    /**
     * Service tax applicable on the settlement amount.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tax")
    public Double serviceTax;

    public FetchPGReconData withServiceTax(Double serviceTax) {
        this.serviceTax = serviceTax;
        return this;
    }
    
    /**
     * Settlement charges applicable on the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_charge")
    public Double settlementCharge;

    public FetchPGReconData withSettlementCharge(Double settlementCharge) {
        this.settlementCharge = settlementCharge;
        return this;
    }
    
    /**
     * Date and time when the settlement was processed.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_date")
    public String settlementDate;

    public FetchPGReconData withSettlementDate(String settlementDate) {
        this.settlementDate = settlementDate;
        return this;
    }
    
    /**
     * Date and time when the settlement was initiated.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_initiated_on")
    public String settlementInitiatedOn;

    public FetchPGReconData withSettlementInitiatedOn(String settlementInitiatedOn) {
        this.settlementInitiatedOn = settlementInitiatedOn;
        return this;
    }
    
    /**
     * Settlement tax applicable on the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_tax")
    public Double settlementTax;

    public FetchPGReconData withSettlementTax(Double settlementTax) {
        this.settlementTax = settlementTax;
        return this;
    }
    
    /**
     * Type of settlement. Possible values - Standard, Instant, On demand.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_type")
    public String settlementType;

    public FetchPGReconData withSettlementType(String settlementType) {
        this.settlementType = settlementType;
        return this;
    }
    
    /**
     * Unique transaction reference number of the settlement.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_utr")
    public String settlementUtr;

    public FetchPGReconData withSettlementUtr(String settlementUtr) {
        this.settlementUtr = settlementUtr;
        return this;
    }
    
    /**
     * Service charge that is applicable for splitting the payment.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("split_service_charge")
    public Double splitServiceCharge;

    public FetchPGReconData withSplitServiceCharge(Double splitServiceCharge) {
        this.splitServiceCharge = splitServiceCharge;
        return this;
    }
    
    /**
     * Service tax applicable for splitting the amount to vendors.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("split_service_tax")
    public Double splitServiceTax;

    public FetchPGReconData withSplitServiceTax(Double splitServiceTax) {
        this.splitServiceTax = splitServiceTax;
        return this;
    }
    
    /**
     * Vendor commission applicable for this transaction.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vendor_commission")
    public Double vendorCommission;

    public FetchPGReconData withVendorCommission(Double vendorCommission) {
        this.vendorCommission = vendorCommission;
        return this;
    }
    
    public FetchPGReconData(){}
}
