/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LinkMetaEntity {
    /**
     * Notification URL for server-server communication. It should be an https URL.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notify_url")
    public String notifyUrl;

    public LinkMetaEntity withNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
        return this;
    }
    
    /**
     * Allowed payment modes for this link. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc", "nb", "upi", "paypal", "app". Leave it blank to show all available payment methods
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_methods")
    public String paymentMethods;

    public LinkMetaEntity withPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods;
        return this;
    }
    
    /**
     * The URL to which user will be redirected to after the payment is done on the link. Maximum length: 250.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("return_url")
    public String returnUrl;

    public LinkMetaEntity withReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
        return this;
    }
    
    /**
     * If "true", link will directly open UPI Intent flow on mobile, and normal link flow elsewhere
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("upi_intent")
    public Boolean upiIntent;

    public LinkMetaEntity withUpiIntent(Boolean upiIntent) {
        this.upiIntent = upiIntent;
        return this;
    }
    
    public LinkMetaEntity(){}
}
