/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LinkOrdersResponse {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_order_id")
    public Long cfOrderId;

    public LinkOrdersResponse withCfOrderId(Long cfOrderId) {
        this.cfOrderId = cfOrderId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_details")
    public LinkCustomerDetailsEntity customerDetails;

    public LinkOrdersResponse withCustomerDetails(LinkCustomerDetailsEntity customerDetails) {
        this.customerDetails = customerDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity")
    public String entity;

    public LinkOrdersResponse withEntity(String entity) {
        this.entity = entity;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_amount")
    public Double orderAmount;

    public LinkOrdersResponse withOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_currency")
    public String orderCurrency;

    public LinkOrdersResponse withOrderCurrency(String orderCurrency) {
        this.orderCurrency = orderCurrency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_expiry_time")
    public String orderExpiryTime;

    public LinkOrdersResponse withOrderExpiryTime(String orderExpiryTime) {
        this.orderExpiryTime = orderExpiryTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public LinkOrdersResponse withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_note")
    public String orderNote;

    public LinkOrdersResponse withOrderNote(String orderNote) {
        this.orderNote = orderNote;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_status")
    public String orderStatus;

    public LinkOrdersResponse withOrderStatus(String orderStatus) {
        this.orderStatus = orderStatus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_token")
    public String orderToken;

    public LinkOrdersResponse withOrderToken(String orderToken) {
        this.orderToken = orderToken;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payments")
    public PaymentURLObject payments;

    public LinkOrdersResponse withPayments(PaymentURLObject payments) {
        this.payments = payments;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refunds")
    public RefundURLObject refunds;

    public LinkOrdersResponse withRefunds(RefundURLObject refunds) {
        this.refunds = refunds;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlements")
    public SettlementURLObject settlements;

    public LinkOrdersResponse withSettlements(SettlementURLObject settlements) {
        this.settlements = settlements;
        return this;
    }
    
    public LinkOrdersResponse(){}
}
