/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class LinkCustomerDetailsEntity {
    /**
     * Customer email address
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_email")
    public String customerEmail;

    public LinkCustomerDetailsEntity withCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
        return this;
    }
    
    /**
     * Customer name
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_name")
    public String customerName;

    public LinkCustomerDetailsEntity withCustomerName(String customerName) {
        this.customerName = customerName;
        return this;
    }
    
    /**
     * Customer phone number
     */
    @JsonProperty("customer_phone")
    public String customerPhone;

    public LinkCustomerDetailsEntity withCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
        return this;
    }
    
    public LinkCustomerDetailsEntity(@JsonProperty("customer_phone") String customerPhone) {
        this.customerPhone = customerPhone;
  }
}
