/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LinkCancelledError - Cannot cancel Payment Link if status is not ACTIVE
 */

public class LinkCancelledError {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("code")
    public String code;

    public LinkCancelledError withCode(String code) {
        this.code = code;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public LinkCancelledError withMessage(String message) {
        this.message = message;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public String type;

    public LinkCancelledError withType(String type) {
        this.type = type;
        return this;
    }
    
    public LinkCancelledError(){}
}
