/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class Netbanking {
    /**
     * The channel for netbanking will always be `link`
     */
    @JsonProperty("channel")
    public String channel;

    public Netbanking withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    /**
     * Bank code
     */
    @JsonProperty("netbanking_bank_code")
    public Integer netbankingBankCode;

    public Netbanking withNetbankingBankCode(Integer netbankingBankCode) {
        this.netbankingBankCode = netbankingBankCode;
        return this;
    }
    
    public Netbanking(@JsonProperty("channel") String channel, @JsonProperty("netbanking_bank_code") Integer netbankingBankCode) {
        this.channel = channel;
        this.netbankingBankCode = netbankingBankCode;
  }
}
