/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class NetBankingPaymentMethod {
    @JsonProperty("netbanking")
    public Netbanking netbanking;

    public NetBankingPaymentMethod withNetbanking(Netbanking netbanking) {
        this.netbanking = netbanking;
        return this;
    }
    
    public NetBankingPaymentMethod(@JsonProperty("netbanking") Netbanking netbanking) {
        this.netbanking = netbanking;
  }
}
