/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferWallet {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("app")
    public WalletOffer app;

    public OfferWallet withApp(WalletOffer app) {
        this.app = app;
        return this;
    }
    
    public OfferWallet(){}
}
