/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferQueries {
    /**
     * Amount of the order. OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    public Double amount;

    public OfferQueries withAmount(Double amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * OrderId of the order. Either of `order_id` or `order_amount` is mandatory.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public OfferQueries withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    public OfferQueries(){}
}
