/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * OfferEntity - OK
 */

public class OfferEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_details")
    public OfferDetails offerDetails;

    public OfferEntity withOfferDetails(OfferDetails offerDetails) {
        this.offerDetails = offerDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_id")
    public Long offerId;

    public OfferEntity withOfferId(Long offerId) {
        this.offerId = offerId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_meta")
    public OfferMeta offerMeta;

    public OfferEntity withOfferMeta(OfferMeta offerMeta) {
        this.offerMeta = offerMeta;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_status")
    public String offerStatus;

    public OfferEntity withOfferStatus(String offerStatus) {
        this.offerStatus = offerStatus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_tnc")
    public OfferTnc offerTnc;

    public OfferEntity withOfferTnc(OfferTnc offerTnc) {
        this.offerTnc = offerTnc;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_validations")
    public OfferValidations offerValidations;

    public OfferEntity withOfferValidations(OfferValidations offerValidations) {
        this.offerValidations = offerValidations;
        return this;
    }
    
    public OfferEntity(){}
}
