/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferDetails {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cashback_details")
    public CashbackDetails cashbackDetails;

    public OfferDetails withCashbackDetails(CashbackDetails cashbackDetails) {
        this.cashbackDetails = cashbackDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("discount_details")
    public DiscountDetails discountDetails;

    public OfferDetails withDiscountDetails(DiscountDetails discountDetails) {
        this.discountDetails = discountDetails;
        return this;
    }
    
    /**
     * Offer Type for the Offer.
     */
    @JsonProperty("offer_type")
    public OfferDetailsOfferType offerType;

    public OfferDetails withOfferType(OfferDetailsOfferType offerType) {
        this.offerType = offerType;
        return this;
    }
    
    public OfferDetails(@JsonProperty("offer_type") OfferDetailsOfferType offerType) {
        this.offerType = offerType;
  }
}
