/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferValidations {
    /**
     * Maximum amount of Offer that can be availed.
     */
    @JsonProperty("max_allowed")
    public String maxAllowed;

    public OfferValidations withMaxAllowed(String maxAllowed) {
        this.maxAllowed = maxAllowed;
        return this;
    }
    
    /**
     * Minimum Amount for Offer to be Applicable
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("min_amount")
    public String minAmount;

    public OfferValidations withMinAmount(String minAmount) {
        this.minAmount = minAmount;
        return this;
    }
    
    @JsonProperty("payment_method")
    public Object paymentMethod;

    public OfferValidations withPaymentMethod(Object paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    public OfferValidations(@JsonProperty("max_allowed") String maxAllowed, @JsonProperty("payment_method") Object paymentMethod) {
        this.maxAllowed = maxAllowed;
        this.paymentMethod = paymentMethod;
  }
}
