/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OfferTncOfferTncType - TnC Type for the Offer. It can be either `text` or `link`
 */
public enum OfferTncOfferTncType {
    LINK("link"),
    POST("post");

    @JsonValue
    public final String value;

    private OfferTncOfferTncType(String value) {
        this.value = value;
    }
}
