/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferEMI {
    @JsonProperty("emi")
    public EMIOffer emi;

    public OfferEMI withEmi(EMIOffer emi) {
        this.emi = emi;
        return this;
    }
    
    public OfferEMI(@JsonProperty("emi") EMIOffer emi) {
        this.emi = emi;
  }
}
