/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferPaylater {
    @JsonProperty("paylater")
    public PaylaterOffer paylater;

    public OfferPaylater withPaylater(PaylaterOffer paylater) {
        this.paylater = paylater;
        return this;
    }
    
    public OfferPaylater(@JsonProperty("paylater") PaylaterOffer paylater) {
        this.paylater = paylater;
  }
}
