/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferCard {
    @JsonProperty("card")
    public CardOffer card;

    public OfferCard withCard(CardOffer card) {
        this.card = card;
        return this;
    }
    
    public OfferCard(@JsonProperty("card") CardOffer card) {
        this.card = card;
  }
}
