/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class OfferAll {
    @JsonProperty("all")
    public All all;

    public OfferAll withAll(All all) {
        this.all = all;
        return this;
    }
    
    public OfferAll(@JsonProperty("all") All all) {
        this.all = all;
  }
}
