/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OrderPayRequest {
    /**
     * This is required if any offers needs to be applied to the order.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("offer_id")
    public String offerId;

    public OrderPayRequest withOfferId(String offerId) {
        this.offerId = offerId;
        return this;
    }
    
    @JsonProperty("payment_method")
    public Object paymentMethod;

    public OrderPayRequest withPaymentMethod(Object paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    @JsonProperty("payment_session_id")
    public String paymentSessionId;

    public OrderPayRequest withPaymentSessionId(String paymentSessionId) {
        this.paymentSessionId = paymentSessionId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("save_instrument")
    public Boolean saveInstrument;

    public OrderPayRequest withSaveInstrument(Boolean saveInstrument) {
        this.saveInstrument = saveInstrument;
        return this;
    }
    
    public OrderPayRequest(@JsonProperty("payment_method") Object paymentMethod, @JsonProperty("payment_session_id") String paymentSessionId) {
        this.paymentMethod = paymentMethod;
        this.paymentSessionId = paymentSessionId;
  }
}
