/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OrderMeta {
    /**
     * Notification URL for server-server communication. Useful when user's connection drops while re-directing. NotifyUrl should be an https URL. Maximum length: 250.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("notify_url")
    public String notifyUrl;

    public OrderMeta withNotifyUrl(String notifyUrl) {
        this.notifyUrl = notifyUrl;
        return this;
    }
    
    /**
     * Allowed payment modes for this order. Pass comma-separated values among following options - "cc", "dc", "ccc", "ppc","nb","upi","paypal","app","paylater","cardlessemi","dcemi","ccemi","banktransfer". Leave it blank to show all available payment methods
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_methods")
    public String paymentMethods;

    public OrderMeta withPaymentMethods(String paymentMethods) {
        this.paymentMethods = paymentMethods;
        return this;
    }
    
    /**
     * The URL to which user will be redirected to after the payment on bank OTP page. Maximum length: 250. The return_url must contain placeholder {order_id}. When redirecting the customer back to the return url from the bank’s OTP page, Cashfree will replace this placeholder with the actual value for that order.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("return_url")
    public String returnUrl;

    public OrderMeta withReturnUrl(String returnUrl) {
        this.returnUrl = returnUrl;
        return this;
    }
    
    public OrderMeta(){}
}
