/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrderPayResponseAction - One of ["link", "custom", "form"]
 */
public enum OrderPayResponseAction {
    LINK("link"),
    CUSTOM("custom"),
    FORM("form");

    @JsonValue
    public final String value;

    private OrderPayResponseAction(String value) {
        this.value = value;
    }
}
