/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OrderPayResponseChannel - One of ["link", "collect", "qrcode"]. In an older version we used to support different channels like 'gpay', 'phonepe' etc. However, we now support only the following channels - link, collect and qrcode. To process payments using gpay, you will have to provide channel as 'link' and provider as 'gpay'
 */
public enum OrderPayResponseChannel {
    LINK("link"),
    COLLECT("collect"),
    QRCODE("qrcode");

    @JsonValue
    public final String value;

    private OrderPayResponseChannel(String value) {
        this.value = value;
    }
}
