/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OTPResponseEntityAction - The action that was invoked for this request.
 */
public enum OTPResponseEntityAction {
    SUBMIT_OTP("SUBMIT_OTP"),
    RESEND_OTP("RESEND_OTP");

    @JsonValue
    public final String value;

    private OTPResponseEntityAction(String value) {
        this.value = value;
    }
}
