/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OTPRequestAction - The action for this workflow. Could be either SUBMIT_OTP or RESEND_OTP
 */
public enum OTPRequestAction {
    SUBMIT_OTP("SUBMIT_OTP"),
    RESEND_OTP("RESEND_OTP");

    @JsonValue
    public final String value;

    private OTPRequestAction(String value) {
        this.value = value;
    }
}
