/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * OTPResponseEntityAuthenticateStatus - Status of the is action. Will be either failed or successful. If the action is successful, you should still call the authorization status to verify the final payment status.
 */
public enum OTPResponseEntityAuthenticateStatus {
    FAILED("FAILED"),
    SUCCESS("SUCCESS");

    @JsonValue
    public final String value;

    private OTPResponseEntityAuthenticateStatus(String value) {
        this.value = value;
    }
}
