/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class PaylaterPaymentMethod {
    @JsonProperty("paylater")
    public Paylater paylater;

    public PaylaterPaymentMethod withPaylater(Paylater paylater) {
        this.paylater = paylater;
        return this;
    }
    
    public PaylaterPaymentMethod(@JsonProperty("paylater") Paylater paylater) {
        this.paylater = paylater;
  }
}
