/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodPaylaterInPaymentsEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;

    public PaymentMethodPaylaterInPaymentsEntity withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("phone")
    public String phone;

    public PaymentMethodPaylaterInPaymentsEntity withPhone(String phone) {
        this.phone = phone;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("provider")
    public String provider;

    public PaymentMethodPaylaterInPaymentsEntity withProvider(String provider) {
        this.provider = provider;
        return this;
    }
    
    public PaymentMethodPaylaterInPaymentsEntity(){}
}
