/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentSuccessWebhook {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    public WHdata data;

    public PaymentSuccessWebhook withData(WHdata data) {
        this.data = data;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("event_time")
    public String eventTime;

    public PaymentSuccessWebhook withEventTime(String eventTime) {
        this.eventTime = eventTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    public String type;

    public PaymentSuccessWebhook withType(String type) {
        this.type = type;
        return this;
    }
    
    public PaymentSuccessWebhook(){}
}
