/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * PaymentsEntityPaymentStatus - The transaction status can be one of  ["SUCCESS", "NOT_ATTEMPTED", "FAILED", "USER_DROPPED", "VOID", "CANCELLED", "PENDING"]
 */
public enum PaymentsEntityPaymentStatus {
    SUCCESS("SUCCESS"),
    NOT_ATTEMPTED("NOT_ATTEMPTED"),
    FAILED("FAILED"),
    USER_DROPPED("USER_DROPPED"),
    VOID_("VOID"),
    CANCELLED("CANCELLED"),
    PENDING("PENDING");

    @JsonValue
    public final String value;

    private PaymentsEntityPaymentStatus(String value) {
        this.value = value;
    }
}
