/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodInPaymentsEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_method")
    public Object paymentMethod;

    public PaymentMethodInPaymentsEntity withPaymentMethod(Object paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    public PaymentMethodInPaymentsEntity(){}
}
