/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodUPIInPaymentsEntity {
    @JsonProperty("channel")
    public String channel;

    public PaymentMethodUPIInPaymentsEntity withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("upi_id")
    public String upiId;

    public PaymentMethodUPIInPaymentsEntity withUpiId(String upiId) {
        this.upiId = upiId;
        return this;
    }
    
    public PaymentMethodUPIInPaymentsEntity(@JsonProperty("channel") String channel) {
        this.channel = channel;
  }
}
