/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PaymentMethodCardInPaymentsEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_bank_name")
    public String cardBankName;

    public PaymentMethodCardInPaymentsEntity withCardBankName(String cardBankName) {
        this.cardBankName = cardBankName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_country")
    public String cardCountry;

    public PaymentMethodCardInPaymentsEntity withCardCountry(String cardCountry) {
        this.cardCountry = cardCountry;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_network")
    public String cardNetwork;

    public PaymentMethodCardInPaymentsEntity withCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_network_reference_id")
    public String cardNetworkReferenceId;

    public PaymentMethodCardInPaymentsEntity withCardNetworkReferenceId(String cardNetworkReferenceId) {
        this.cardNetworkReferenceId = cardNetworkReferenceId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_number")
    public String cardNumber;

    public PaymentMethodCardInPaymentsEntity withCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_type")
    public String cardType;

    public PaymentMethodCardInPaymentsEntity withCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;

    public PaymentMethodCardInPaymentsEntity withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    public PaymentMethodCardInPaymentsEntity(){}
}
