/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RefundsEntityRefundType - This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"]
 */
public enum RefundsEntityRefundType {
    PAYMENT_AUTO_REFUND("PAYMENT_AUTO_REFUND"),
    MERCHANT_INITIATED("MERCHANT_INITIATED"),
    UNRECONCILED_AUTO_REFUND("UNRECONCILED_AUTO_REFUND");

    @JsonValue
    public final String value;

    private RefundsEntityRefundType(String value) {
        this.value = value;
    }
}
