/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class RefundURLObject {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("url")
    public String url;

    public RefundURLObject withUrl(String url) {
        this.url = url;
        return this;
    }
    
    public RefundURLObject(){}
}
