/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RefundsEntityRefundMode - Method or speed of processing refund
 */
public enum RefundsEntityRefundMode {
    STANDARD("STANDARD"),
    INSTANT("INSTANT");

    @JsonValue
    public final String value;

    private RefundsEntityRefundMode(String value) {
        this.value = value;
    }
}
