/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RefundsEntity - Refund created
 */

public class RefundsEntity {
    /**
     * Cashfree Payments ID of the payment for which refund is initiated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_payment_id")
    public Long cfPaymentId;

    public RefundsEntity withCfPaymentId(Long cfPaymentId) {
        this.cfPaymentId = cfPaymentId;
        return this;
    }
    
    /**
     * Cashfree Payments ID for a refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_refund_id")
    public String cfRefundId;

    public RefundsEntity withCfRefundId(String cfRefundId) {
        this.cfRefundId = cfRefundId;
        return this;
    }
    
    /**
     * Time of refund creation
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("created_at")
    public String createdAt;

    public RefundsEntity withCreatedAt(String createdAt) {
        this.createdAt = createdAt;
        return this;
    }
    
    /**
     * Type of object
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity")
    public RefundsEntityEntity entity;

    public RefundsEntity withEntity(RefundsEntityEntity entity) {
        this.entity = entity;
        return this;
    }
    
    /**
     * Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("metadata")
    public RefundsEntityMetadata metadata;

    public RefundsEntity withMetadata(RefundsEntityMetadata metadata) {
        this.metadata = metadata;
        return this;
    }
    
    /**
     * Merchant’s order Id of the order for which refund is initiated
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public RefundsEntity withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    /**
     * Time when refund was processed successfully
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("processed_at")
    public String processedAt;

    public RefundsEntity withProcessedAt(String processedAt) {
        this.processedAt = processedAt;
        return this;
    }
    
    /**
     * Amount that is refunded
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_amount")
    public Double refundAmount;

    public RefundsEntity withRefundAmount(Double refundAmount) {
        this.refundAmount = refundAmount;
        return this;
    }
    
    /**
     * The bank reference number for refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_arn")
    public String refundArn;

    public RefundsEntity withRefundArn(String refundArn) {
        this.refundArn = refundArn;
        return this;
    }
    
    /**
     * Charges in INR for processing refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_charge")
    public Double refundCharge;

    public RefundsEntity withRefundCharge(Double refundCharge) {
        this.refundCharge = refundCharge;
        return this;
    }
    
    /**
     * Currency of the refund amount
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_currency")
    public String refundCurrency;

    public RefundsEntity withRefundCurrency(String refundCurrency) {
        this.refundCurrency = refundCurrency;
        return this;
    }
    
    /**
     * Merchant’s refund ID of the refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_id")
    public String refundId;

    public RefundsEntity withRefundId(String refundId) {
        this.refundId = refundId;
        return this;
    }
    
    /**
     * Method or speed of processing refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_mode")
    public RefundsEntityRefundMode refundMode;

    public RefundsEntity withRefundMode(RefundsEntityRefundMode refundMode) {
        this.refundMode = refundMode;
        return this;
    }
    
    /**
     * Note added by merchant for the refund
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_note")
    public String refundNote;

    public RefundsEntity withRefundNote(String refundNote) {
        this.refundNote = refundNote;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_speed")
    public RefundSpeed refundSpeed;

    public RefundsEntity withRefundSpeed(RefundSpeed refundSpeed) {
        this.refundSpeed = refundSpeed;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_splits")
    public VendorSplit[] refundSplits;

    public RefundsEntity withRefundSplits(VendorSplit[] refundSplits) {
        this.refundSplits = refundSplits;
        return this;
    }
    
    /**
     * This can be one of ["SUCCESS", "PENDING", "CANCELLED", "ONHOLD", "FAILED"]
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_status")
    public RefundsEntityRefundStatus refundStatus;

    public RefundsEntity withRefundStatus(RefundsEntityRefundStatus refundStatus) {
        this.refundStatus = refundStatus;
        return this;
    }
    
    /**
     * This can be one of ["PAYMENT_AUTO_REFUND", "MERCHANT_INITIATED", "UNRECONCILED_AUTO_REFUND"]
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("refund_type")
    public RefundsEntityRefundType refundType;

    public RefundsEntity withRefundType(RefundsEntityRefundType refundType) {
        this.refundType = refundType;
        return this;
    }
    
    /**
     * Description of refund status
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("status_description")
    public String statusDescription;

    public RefundsEntity withStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
        return this;
    }
    
    public RefundsEntity(){}
}
