/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * RefundsEntityRefundStatus - This can be one of ["SUCCESS", "PENDING", "CANCELLED", "ONHOLD", "FAILED"]
 */
public enum RefundsEntityRefundStatus {
    SUCCESS("SUCCESS"),
    PENDING("PENDING"),
    CANCELLED("CANCELLED"),
    ONHOLD("ONHOLD");

    @JsonValue
    public final String value;

    private RefundsEntityRefundStatus(String value) {
        this.value = value;
    }
}
