/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;



/**
 * RefundsEntityMetadata - Key-value pair that can be used to store additional information about the entity. Maximum 5 key-value pairs
 */

public class RefundsEntityMetadata {
    public RefundsEntityMetadata(){}
}
