/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class RefundSpeed {
    /**
     * Accepted speed of refund.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("accepted")
    public String accepted;

    public RefundSpeed withAccepted(String accepted) {
        this.accepted = accepted;
        return this;
    }
    
    /**
     * Error message, if any for refund_speed request
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("message")
    public String message;

    public RefundSpeed withMessage(String message) {
        this.message = message;
        return this;
    }
    
    /**
     * Processed speed of refund.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("processed")
    public String processed;

    public RefundSpeed withProcessed(String processed) {
        this.processed = processed;
        return this;
    }
    
    /**
     * Requested speed of refund.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("requested")
    public String requested;

    public RefundSpeed withRequested(String requested) {
        this.requested = requested;
        return this;
    }
    
    public RefundSpeed(){}
}
