/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class SavedInstrumentMeta {
    /**
     * Issuing bank name of saved card
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_bank_name")
    public String cardBankName;

    public SavedInstrumentMeta withCardBankName(String cardBankName) {
        this.cardBankName = cardBankName;
        return this;
    }
    
    /**
     * Issuing country of saved card
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_country")
    public String cardCountry;

    public SavedInstrumentMeta withCardCountry(String cardCountry) {
        this.cardCountry = cardCountry;
        return this;
    }
    
    /**
     * card scheme/network of the saved card
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_network")
    public String cardNetwork;

    public SavedInstrumentMeta withCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_token_details")
    public SavedInstrumentMetaCardTokenDetails cardTokenDetails;

    public SavedInstrumentMeta withCardTokenDetails(SavedInstrumentMetaCardTokenDetails cardTokenDetails) {
        this.cardTokenDetails = cardTokenDetails;
        return this;
    }
    
    /**
     * Type of saved card
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_type")
    public String cardType;

    public SavedInstrumentMeta withCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }
    
    public SavedInstrumentMeta(){}
}
