/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SettlementsEntity - OK
 */

public class SettlementsEntity {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_payment_id")
    public String cfPaymentId;

    public SettlementsEntity withCfPaymentId(String cfPaymentId) {
        this.cfPaymentId = cfPaymentId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_settlement_id")
    public String cfSettlementId;

    public SettlementsEntity withCfSettlementId(String cfSettlementId) {
        this.cfSettlementId = cfSettlementId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("entity")
    public String entity;

    public SettlementsEntity withEntity(String entity) {
        this.entity = entity;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_amount")
    public Double orderAmount;

    public SettlementsEntity withOrderAmount(Double orderAmount) {
        this.orderAmount = orderAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order_id")
    public String orderId;

    public SettlementsEntity withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_time")
    public String paymentTime;

    public SettlementsEntity withPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_charge")
    public Double serviceCharge;

    public SettlementsEntity withServiceCharge(Double serviceCharge) {
        this.serviceCharge = serviceCharge;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("service_tax")
    public Double serviceTax;

    public SettlementsEntity withServiceTax(Double serviceTax) {
        this.serviceTax = serviceTax;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_amount")
    public Double settlementAmount;

    public SettlementsEntity withSettlementAmount(Double settlementAmount) {
        this.settlementAmount = settlementAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_currency")
    public String settlementCurrency;

    public SettlementsEntity withSettlementCurrency(String settlementCurrency) {
        this.settlementCurrency = settlementCurrency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("settlement_id")
    public Long settlementId;

    public SettlementsEntity withSettlementId(Long settlementId) {
        this.settlementId = settlementId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer_id")
    public Long transferId;

    public SettlementsEntity withTransferId(Long transferId) {
        this.transferId = transferId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer_time")
    public String transferTime;

    public SettlementsEntity withTransferTime(String transferTime) {
        this.transferTime = transferTime;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("transfer_utr")
    public String transferUtr;

    public SettlementsEntity withTransferUtr(String transferUtr) {
        this.transferUtr = transferUtr;
        return this;
    }
    
    public SettlementsEntity(){}
}
