/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonValue;

/**
 * UpiChannel - Specify the channel through which the payment must be processed. Can be one of ["link", "collect", "qrcode"]
 */
public enum UpiChannel {
    LINK("link"),
    COLLECT("collect"),
    QRCODE("qrcode");

    @JsonValue
    public final String value;

    private UpiChannel(String value) {
        this.value = value;
    }
}
