/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonProperty;


public class UPIPaymentMethod {
    @JsonProperty("upi")
    public Upi upi;

    public UPIPaymentMethod withUpi(Upi upi) {
        this.upi = upi;
        return this;
    }
    
    public UPIPaymentMethod(@JsonProperty("upi") Upi upi) {
        this.upi = upi;
  }
}
