/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class VendorSplit {
    /**
     * Amount which will be associated with this vendor
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("amount")
    public Double amount;

    public VendorSplit withAmount(Double amount) {
        this.amount = amount;
        return this;
    }
    
    /**
     * Percentage of order amount which shall get added to vendor account
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("percentage")
    public Double percentage;

    public VendorSplit withPercentage(Double percentage) {
        this.percentage = percentage;
        return this;
    }
    
    /**
     * Vendor id created in Cashfree system
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("vendor_id")
    public String vendorId;

    public VendorSplit withVendorId(String vendorId) {
        this.vendorId = vendorId;
        return this;
    }
    
    public VendorSplit(){}
}
