/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class WHcard {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_bank_name")
    public String cardBankName;

    public WHcard withCardBankName(String cardBankName) {
        this.cardBankName = cardBankName;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_county")
    public String cardCounty;

    public WHcard withCardCounty(String cardCounty) {
        this.cardCounty = cardCounty;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_network")
    public String cardNetwork;

    public WHcard withCardNetwork(String cardNetwork) {
        this.cardNetwork = cardNetwork;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_number")
    public String cardNumber;

    public WHcard withCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("card_type")
    public String cardType;

    public WHcard withCardType(String cardType) {
        this.cardType = cardType;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("channel")
    public String channel;

    public WHcard withChannel(String channel) {
        this.channel = channel;
        return this;
    }
    
    public WHcard(){}
}
