/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class WHdata {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("customer_details")
    public WHcustomerDetails customerDetails;

    public WHdata withCustomerDetails(WHcustomerDetails customerDetails) {
        this.customerDetails = customerDetails;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("order")
    public WHorder order;

    public WHdata withOrder(WHorder order) {
        this.order = order;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment")
    public WHpayment payment;

    public WHdata withPayment(WHpayment payment) {
        this.payment = payment;
        return this;
    }
    
    public WHdata(){}
}
