/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;


public class WHpayment {
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("auth_id")
    public String authId;

    public WHpayment withAuthId(String authId) {
        this.authId = authId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("bank_reference")
    public String bankReference;

    public WHpayment withBankReference(String bankReference) {
        this.bankReference = bankReference;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cf_payment_id")
    public String cfPaymentId;

    public WHpayment withCfPaymentId(String cfPaymentId) {
        this.cfPaymentId = cfPaymentId;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_amount")
    public Double paymentAmount;

    public WHpayment withPaymentAmount(Double paymentAmount) {
        this.paymentAmount = paymentAmount;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_currency")
    public String paymentCurrency;

    public WHpayment withPaymentCurrency(String paymentCurrency) {
        this.paymentCurrency = paymentCurrency;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_group")
    public String paymentGroup;

    public WHpayment withPaymentGroup(String paymentGroup) {
        this.paymentGroup = paymentGroup;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_message")
    public String paymentMessage;

    public WHpayment withPaymentMessage(String paymentMessage) {
        this.paymentMessage = paymentMessage;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_method")
    public WHpaymentMethod paymentMethod;

    public WHpayment withPaymentMethod(WHpaymentMethod paymentMethod) {
        this.paymentMethod = paymentMethod;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_status")
    public String paymentStatus;

    public WHpayment withPaymentStatus(String paymentStatus) {
        this.paymentStatus = paymentStatus;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("payment_time")
    public String paymentTime;

    public WHpayment withPaymentTime(String paymentTime) {
        this.paymentTime = paymentTime;
        return this;
    }
    
    public WHpayment(){}
}
