/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class CreateOrderResponse {
    /**
     * API related Errors
     */
    
    public Cashfree.PG_Latest.models.shared.ApiError apiError;

    public CreateOrderResponse withApiError(Cashfree.PG_Latest.models.shared.ApiError apiError) {
        this.apiError = apiError;
        return this;
    }
    
    /**
     * Authentication Error
     */
    
    public Cashfree.PG_Latest.models.shared.AuthenticationError authenticationError;

    public CreateOrderResponse withAuthenticationError(Cashfree.PG_Latest.models.shared.AuthenticationError authenticationError) {
        this.authenticationError = authenticationError;
        return this;
    }
    
    
    public String contentType;

    public CreateOrderResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Any bad or invalid request will lead to following error object
     */
    
    public Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse;

    public CreateOrderResponse withErrorResponse(Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public CreateOrderResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.OrdersEntity ordersEntity;

    public CreateOrderResponse withOrdersEntity(Cashfree.PG_Latest.models.shared.OrdersEntity ordersEntity) {
        this.ordersEntity = ordersEntity;
        return this;
    }
    
    /**
     * Rate Limit Error
     */
    
    public Cashfree.PG_Latest.models.shared.RateLimitError rateLimitError;

    public CreateOrderResponse withRateLimitError(Cashfree.PG_Latest.models.shared.RateLimitError rateLimitError) {
        this.rateLimitError = rateLimitError;
        return this;
    }
    
    
    public Integer statusCode;

    public CreateOrderResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public CreateOrderResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public CreateOrderResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
