/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class DeleteSpecificSavedInstrumentResponse {
    
    public String contentType;

    public DeleteSpecificSavedInstrumentResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Any bad or invalid request will lead to following error object
     */
    
    public Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse;

    public DeleteSpecificSavedInstrumentResponse withErrorResponse(Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.FetchAllSavedInstruments fetchAllSavedInstruments;

    public DeleteSpecificSavedInstrumentResponse withFetchAllSavedInstruments(Cashfree.PG_Latest.models.shared.FetchAllSavedInstruments fetchAllSavedInstruments) {
        this.fetchAllSavedInstruments = fetchAllSavedInstruments;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public DeleteSpecificSavedInstrumentResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;

    public DeleteSpecificSavedInstrumentResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public DeleteSpecificSavedInstrumentResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public DeleteSpecificSavedInstrumentResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
