/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class EligibilityPaylaterResponse {
    
    public String contentType;

    public EligibilityPaylaterResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.EligiblePaylater[] eligiblePaylaters;

    public EligibilityPaylaterResponse withEligiblePaylaters(Cashfree.PG_Latest.models.shared.EligiblePaylater[] eligiblePaylaters) {
        this.eligiblePaylaters = eligiblePaylaters;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public EligibilityPaylaterResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;

    public EligibilityPaylaterResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public EligibilityPaylaterResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public EligibilityPaylaterResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
