/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class EligibilityOfferResponse {
    
    public String contentType;

    public EligibilityOfferResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.EligibleOffersEntity[] eligibleOffersEntities;

    public EligibilityOfferResponse withEligibleOffersEntities(Cashfree.PG_Latest.models.shared.EligibleOffersEntity[] eligibleOffersEntities) {
        this.eligibleOffersEntities = eligibleOffersEntities;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public EligibilityOfferResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;

    public EligibilityOfferResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public EligibilityOfferResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public EligibilityOfferResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
