/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class FetchAllSavedInstrumentsRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=customer_id")
    public String customerId;

    public FetchAllSavedInstrumentsRequest withCustomerId(String customerId) {
        this.customerId = customerId;
        return this;
    }
    
    /**
     * type to instrument to query
     */
    @SpeakeasyMetadata("queryParam:style=form,explode=true,name=instrument_type")
    public FetchAllSavedInstrumentsInstrumentType instrumentType;

    public FetchAllSavedInstrumentsRequest withInstrumentType(FetchAllSavedInstrumentsInstrumentType instrumentType) {
        this.instrumentType = instrumentType;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public FetchAllSavedInstrumentsRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-id")
    public String xClientId;

    public FetchAllSavedInstrumentsRequest withXClientId(String xClientId) {
        this.xClientId = xClientId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-secret")
    public String xClientSecret;

    public FetchAllSavedInstrumentsRequest withXClientSecret(String xClientSecret) {
        this.xClientSecret = xClientSecret;
        return this;
    }
    
    public FetchAllSavedInstrumentsRequest(@JsonProperty("customer_id") String customerId, @JsonProperty("instrument_type") FetchAllSavedInstrumentsInstrumentType instrumentType, @JsonProperty("x-client-id") String xClientId, @JsonProperty("x-client-secret") String xClientSecret) {
        this.customerId = customerId;
        this.instrumentType = instrumentType;
        this.xClientId = xClientId;
        this.xClientSecret = xClientSecret;
  }
}
