/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class GetPaymentLinkOrdersResponse {
    
    public String contentType;

    public GetPaymentLinkOrdersResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public GetPaymentLinkOrdersResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.LinkOrdersResponse[] linkOrdersResponses;

    public GetPaymentLinkOrdersResponse withLinkOrdersResponses(Cashfree.PG_Latest.models.shared.LinkOrdersResponse[] linkOrdersResponses) {
        this.linkOrdersResponses = linkOrdersResponses;
        return this;
    }
    
    
    public Integer statusCode;

    public GetPaymentLinkOrdersResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public GetPaymentLinkOrdersResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public GetPaymentLinkOrdersResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
