/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetPaymentbyIdRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=cf_payment_id")
    public Long cfPaymentId;

    public GetPaymentbyIdRequest withCfPaymentId(Long cfPaymentId) {
        this.cfPaymentId = cfPaymentId;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=order_id")
    public String orderId;

    public GetPaymentbyIdRequest withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public GetPaymentbyIdRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-id")
    public String xClientId;

    public GetPaymentbyIdRequest withXClientId(String xClientId) {
        this.xClientId = xClientId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-secret")
    public String xClientSecret;

    public GetPaymentbyIdRequest withXClientSecret(String xClientSecret) {
        this.xClientSecret = xClientSecret;
        return this;
    }
    
    public GetPaymentbyIdRequest(@JsonProperty("cf_payment_id") Long cfPaymentId, @JsonProperty("order_id") String orderId, @JsonProperty("x-client-id") String xClientId, @JsonProperty("x-client-secret") String xClientSecret) {
        this.cfPaymentId = cfPaymentId;
        this.orderId = orderId;
        this.xClientId = xClientId;
        this.xClientSecret = xClientSecret;
  }
}
