/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class GetTerminalByMobileNumberRequest {
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=terminal_phone_no")
    public String terminalPhoneNo;

    public GetTerminalByMobileNumberRequest withTerminalPhoneNo(String terminalPhoneNo) {
        this.terminalPhoneNo = terminalPhoneNo;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public GetTerminalByMobileNumberRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-id")
    public String xClientId;

    public GetTerminalByMobileNumberRequest withXClientId(String xClientId) {
        this.xClientId = xClientId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-secret")
    public String xClientSecret;

    public GetTerminalByMobileNumberRequest withXClientSecret(String xClientSecret) {
        this.xClientSecret = xClientSecret;
        return this;
    }
    
    public GetTerminalByMobileNumberRequest(@JsonProperty("terminal_phone_no") String terminalPhoneNo, @JsonProperty("x-client-id") String xClientId, @JsonProperty("x-client-secret") String xClientSecret) {
        this.terminalPhoneNo = terminalPhoneNo;
        this.xClientId = xClientId;
        this.xClientSecret = xClientSecret;
  }
}
