/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class OrderPayRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Cashfree.PG_Latest.models.shared.OrderPayRequest orderPayRequest;

    public OrderPayRequest withOrderPayRequest(Cashfree.PG_Latest.models.shared.OrderPayRequest orderPayRequest) {
        this.orderPayRequest = orderPayRequest;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public OrderPayRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    public OrderPayRequest(@JsonProperty("x-api-version") String xApiVersion) {
        this.xApiVersion = xApiVersion;
  }
}
