/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PostReconRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Cashfree.PG_Latest.models.shared.FetchPGReconRequest fetchPGReconRequest;

    public PostReconRequest withFetchPGReconRequest(Cashfree.PG_Latest.models.shared.FetchPGReconRequest fetchPGReconRequest) {
        this.fetchPGReconRequest = fetchPGReconRequest;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public PostReconRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-id")
    public String xClientId;

    public PostReconRequest withXClientId(String xClientId) {
        this.xClientId = xClientId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-secret")
    public String xClientSecret;

    public PostReconRequest withXClientSecret(String xClientSecret) {
        this.xClientSecret = xClientSecret;
        return this;
    }
    
    public PostReconRequest(@JsonProperty("x-client-id") String xClientId, @JsonProperty("x-client-secret") String xClientSecret) {
        this.xClientId = xClientId;
        this.xClientSecret = xClientSecret;
  }
}
