/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.net.http.HttpResponse;


public class PostReconResponse {
    
    public String contentType;

    public PostReconResponse withContentType(String contentType) {
        this.contentType = contentType;
        return this;
    }
    
    /**
     * Any bad or invalid request will lead to following error object
     */
    
    public Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse;

    public PostReconResponse withErrorResponse(Cashfree.PG_Latest.models.shared.ErrorResponse errorResponse) {
        this.errorResponse = errorResponse;
        return this;
    }
    
    /**
     * OK
     */
    
    public Cashfree.PG_Latest.models.shared.FetchPGRecon fetchPGRecon;

    public PostReconResponse withFetchPGRecon(Cashfree.PG_Latest.models.shared.FetchPGRecon fetchPGRecon) {
        this.fetchPGRecon = fetchPGRecon;
        return this;
    }
    
    
    public java.util.Map<String, String[]> headers;

    public PostReconResponse withHeaders(java.util.Map<String, String[]> headers) {
        this.headers = headers;
        return this;
    }
    
    
    public Integer statusCode;

    public PostReconResponse withStatusCode(Integer statusCode) {
        this.statusCode = statusCode;
        return this;
    }
    
    
    public HttpResponse<byte[]> rawResponse;

    public PostReconResponse withRawResponse(HttpResponse<byte[]> rawResponse) {
        this.rawResponse = rawResponse;
        return this;
    }
    
    public PostReconResponse(@JsonProperty("ContentType") String contentType, @JsonProperty("StatusCode") Integer statusCode) {
        this.contentType = contentType;
        this.statusCode = statusCode;
  }
}
