/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package Cashfree.PG_Latest.models.operations;

import Cashfree.PG_Latest.utils.SpeakeasyMetadata;
import com.fasterxml.jackson.annotation.JsonProperty;


public class PreauthorizationRequest {
    @SpeakeasyMetadata("request:mediaType=application/json")
    public Cashfree.PG_Latest.models.shared.AuthorizationRequest authorizationRequest;

    public PreauthorizationRequest withAuthorizationRequest(Cashfree.PG_Latest.models.shared.AuthorizationRequest authorizationRequest) {
        this.authorizationRequest = authorizationRequest;
        return this;
    }
    
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=order_id")
    public String orderId;

    public PreauthorizationRequest withOrderId(String orderId) {
        this.orderId = orderId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-api-version")
    public String xApiVersion;

    public PreauthorizationRequest withXApiVersion(String xApiVersion) {
        this.xApiVersion = xApiVersion;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-id")
    public String xClientId;

    public PreauthorizationRequest withXClientId(String xClientId) {
        this.xClientId = xClientId;
        return this;
    }
    
    @SpeakeasyMetadata("header:style=simple,explode=false,name=x-client-secret")
    public String xClientSecret;

    public PreauthorizationRequest withXClientSecret(String xClientSecret) {
        this.xClientSecret = xClientSecret;
        return this;
    }
    
    public PreauthorizationRequest(@JsonProperty("order_id") String orderId, @JsonProperty("x-client-id") String xClientId, @JsonProperty("x-client-secret") String xClientSecret) {
        this.orderId = orderId;
        this.xClientId = xClientId;
        this.xClientSecret = xClientSecret;
  }
}
